### ISSUE TITLE
Typos and other errors..

### ISSUE THREAD

**Issue by ashmaroli** [sverrirs/jekyllonwindows#1]
Hi sverrirs, 
Great job on the documentation. However I found a few errors in it..
Namely:
- `1-ruby-and-devkit.md` has **Jenkyl gem** in the pagination.. also in `3-syntax-highlighting.md`..
- `--watch` on jekyll4windows broke only in `3.3.0`.. its fine in `3.1.6 ~> 3.2.x`. I dont know about `<3.1.6`

**Comment by sverrirs** [comment]
Thank you for reporting this. I'll get it fixed immediately.
