### ISSUE TITLE
where is the location of _config.yml

### ISSUE THREAD

**Issue by xuanyusa** [sverrirs/jekyllonwindows#2]
# Cannot find my _config.yml
## e.g.
![confuse](https://cloud.githubusercontent.com/assets/21173181/21431187/46a1af02-c8a1-11e6-833f-eda7ee87f201.PNG)
Could you help me?

**Comment by sverrirs** [comment]
Please refer to the official jekyll documentation :)
https://jekyllrb.com/docs/configuration/

**Comment by xuanyusa** [comment]
Thank you ! I got it .
