### ISSUE TITLE
Cannot install wdm on Windows 10

### ISSUE THREAD

**Issue by siennathesane** [sverrirs/jekyllonwindows#3]
Following the instructions for `gem install wdm` results in:

```shell
PS E:\Programming\Ruby23\devkit> gem install wdm
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing wdm:
        ERROR: Failed to build gem native extension.

    current directory: E:/Programming/Ruby23/lib/ruby/gems/2.3.0/gems/wdm-0.1.1/ext/wdm
E:/Programming/Ruby23/bin/ruby.exe -r ./siteconf20170127-20196-ups7xn.rb extconf.rb
checking for main() in -lkernel32... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.
```

Looking at the build log, here is the error:

```
E:/Programming/Ruby23/include/ruby-2.3.0/ruby/ruby.h:2041:12: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: #include <winsock2.h>
4: #include <windows.h>
5: int main(int argc, char **argv)
6: {
7:   return 0;
8: }
/* end */
```

I don't know Ruby at all, and I'm not seeing any solutions online, do you have a workaround idea for this step? I'm using Windows 10 x64.

**Comment by siennathesane** [comment]
Looks like [#24](https://github.com/Maher4Ever/wdm/issues/24) in the WDM repo addresses this as well.

**Comment by sverrirs** [comment]
Try this https://github.com/oneclick/rubyinstaller/issues/276

**Comment by siennathesane** [comment]
After lots of troubleshooting with the link provided, I was able to determine I had accidentally installed the 32-bit version of the devkit. It worked after that, thanks!

**Comment by sverrirs** [comment]
Ah, yeah that will cause problems @mxplusb ;) thanks for updating me with the solution. I will consider adding it to a FAQ thing at the end.
