### ISSUE TITLE
[question] does the path where gem install is launched count?

### ISSUE THREAD

**Issue by netalex** [sverrirs/jekyllonwindows#5]
new to ruby and gem ecosystem, i have the feeling from this guide that gem install it's ever global, so i launch it every time from c:\RubyDevKit where the tutorial leave you during the installation seps. It's correct? TNX

**Comment by sverrirs** [comment]
The gem will be installed into your ruby installation, not the dev kit. 
The dev kit is only used to compile native extensions and nothing will be installed to that location.
