### ISSUE TITLE
3.5.1 various version conflicts - solved

### ISSUE THREAD

**Issue by netalex** [sverrirs/jekyllonwindows#6]
install following the tutorial, and when launchin get those errors:

`Could not find sass-3.4.25`
(was 3.5.1, installed that version)

`Could not find jekyll-3.5.0`
(downgraded from 3.5.1)

`Could not find minima-2.1.1`
(not present, installed that theme)

`Could not find thread_safe-0.3.6`
(not present, installed that version)

`Could not find tzinfo-1.2.3 tzinfo 1.2.3`
(not present, installed that version)

`Could not find tzinfo-data-1.2017.2`
(not present, installed that version)

then, launching `jekyll build`:
`You have already activated sass 3.5.1, but your Gemfile requires sass 3.4.25. Prepending 'bundle exec' to your command may solve this. (Gem::LoadError)`

`bundle exec jekyll build` was a workaround, but `gem uninstall sass -v 3.5.1` solved it.
`

**Comment by sverrirs** [comment]
Thank you for this write up but it does seem like that problem was the configuration of your local gem file. 

I'm glad you found a solution though. Good luck :)

**Comment by netalex** [comment]
sorry, as stated elsewhere, i'm new to gem world. Tanks anyway and hope it will be useful for someone.
